# include utiluty
include ${UTILITIES_TOP_DIR}/makefile/color_printer.mk

# Project Porperity
kBuildDir := ${BUILD_DIR}
kOutputDir := ${OUTPUT_DIR}

kXSASrcsPath := ${HW_XSA_FILE_PATH}

# Compileries
kXsctCLI := ${XSCT_CLI}

kCC := ${CROSS_COMPILE}gcc
kArch := ${ARCH}

gen_base_dt: ${kXSASrcsPath}

build_fsbl: ${kXSASrcsPath}

build_kernel:

build_uboot:

build_busybox:


clean:

.PHONY: clean