# https://wiki.beyondlogic.org/index.php?title=Cross_Compiling_BusyBox_for_ARM#DropBear_.28Optional.29
./configure --prefix=`pwd`/out --host=arm-linux-gnueabihf --with-zlib=../zlib/out  

kDropbearURL := https://github.com/mkj/dropbear